/*
 * Small Business Credit Analytics API
 * A collection of Mastercard-provided APIs for retrieving merchant metrics that help in making lending decisions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.creditanalytics.api;

import com.mastercard.creditanalytics.main.CreditAnalyticsMain;
import org.junit.Assert;
import org.junit.Test;
import org.openapitools.client.ApiException;

import java.io.IOException;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.UnrecoverableKeyException;
import java.security.cert.CertificateException;

/**
 * Tests to cover CreditAnalyticsMain
 * It consists of simple print statements, so nothing is done beyond making sure it runs start to finish
 */
public class CreditAnalyticsMainTest {
    @Test
    public void runCreditAnalyticsMainTest() throws ApiException, UnrecoverableKeyException, CertificateException, IOException, KeyStoreException, NoSuchAlgorithmException {
        CreditAnalyticsMain.main(new String[0]);
    }
    
}
