/*
 * Small Business Credit Analytics API
 * A collection of Mastercard-provided APIs for retrieving merchant metrics that help in making lending decisions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.creditanalytics.api;

import org.junit.Assert;
import org.openapitools.client.ApiException;
import org.junit.Test;

import java.io.IOException;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.UnrecoverableKeyException;
import java.security.cert.CertificateException;

/**
 * API tests for MatchingApi
 */
public class MatchingApiTest {
   @Test
    public void getMatchesTest() throws ApiException, UnrecoverableKeyException, CertificateException, IOException, KeyStoreException, NoSuchAlgorithmException {
        Assert.assertNotNull(ApiExamples.getSingleMatchByNameAndAddress());
        Assert.assertNotNull(ApiExamples.getMultipleMatchesByNameAndAddress());
        Assert.assertNotNull(ApiExamples.getSingleMatchByMID());
        Assert.assertNotNull(ApiExamples.getMultipleMatchByMID());

        // Matches error examples
        Assert.assertThrows(ApiException.class, ApiExamples::throwsNoMatchFoundByNameAndAddress);
        Assert.assertThrows(ApiException.class, ApiExamples::throwsInvalidPostalCodeApiException);
        Assert.assertThrows(ApiException.class, ApiExamples::throwsGetInvalidStateProvinceCodeApiException);
        Assert.assertThrows(ApiException.class, ApiExamples::throwsInvalidCountryCodeApiException);
        Assert.assertThrows(ApiException.class, ApiExamples::throwsInvalidIDType);
        Assert.assertThrows(ApiException.class, ApiExamples::throwsNoMatchFoundByMID);
    }
}
