/*
 * Small Business Credit Analytics API
 * A collection of Mastercard-provided APIs for retrieving merchant metrics that help in making lending decisions.
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: apisupport@mastercard.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.mastercard.creditanalytics.api;

import org.junit.Assert;
import org.junit.Test;
import org.openapitools.client.ApiException;

import java.io.IOException;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.UnrecoverableKeyException;
import java.security.cert.CertificateException;

/**
 * API tests for MetricsApi
 */
public class MetricsApiTest {
    @Test
    public void getMetricsTest() throws ApiException, UnrecoverableKeyException, CertificateException, IOException, KeyStoreException, NoSuchAlgorithmException {
        Assert.assertNotNull(ApiExamples.getFullyPopulatedWeeklyMetrics());

        Assert.assertNotNull(ApiExamples.getFullyPopulateMonthlyMetrics());
        Assert.assertNotNull(ApiExamples.getMerchantWithLowTransactionVolumeMonthlyMetrics());
        Assert.assertNotNull(ApiExamples.getMerchantWithLowTransactionVolumeWeeklyMetrics());
        Assert.assertNotNull(ApiExamples.getMerchantWithNoDataFromCurrentOrPreviousYearYoyMonthlyMetrics());
        Assert.assertNotNull(ApiExamples.getMerchantWithNoDataFromCurrentOrPreviousYearYoyWeeklyMetrics());
        Assert.assertNotNull(ApiExamples.getMerchantWithLessThan52WeeksMetrics());
        Assert.assertNotNull(ApiExamples.getMerchantWithLessThan52WeeksMonthlyMetrics());
        Assert.assertThrows(ApiException.class, ApiExamples::throwsMetricsNotFound);
        Assert.assertThrows(ApiException.class, ApiExamples::throwsLocationNotFoundForMonthly);
        Assert.assertThrows(ApiException.class, ApiExamples::throwsLocationNotFoundForWeekly);
        Assert.assertThrows(ApiException.class, ApiExamples::throwsMonthlyConsentNotProvided);
        Assert.assertThrows(ApiException.class, ApiExamples::throwsWeeklyConsentNotProvided);
        Assert.assertThrows(ApiException.class, ApiExamples::throwsMetricFrequencyNotFound);
        //Benchmarks metrics test cases
        Assert.assertNotNull(ApiExamples.getFullyPopulatedBenchmarksMetrics());
        Assert.assertNotNull(ApiExamples.getMerchantWithLowTransactionVolumeBenchmarksMetrics());

        Assert.assertThrows(ApiException.class, ApiExamples::throwsBenchmarksMetricsNotFound);
        Assert.assertThrows(ApiException.class, ApiExamples::throwsBenchmarksMetricsLocationNotFound);
        Assert.assertThrows(ApiException.class, ApiExamples::throwsBenchmarksMetricsConsentNotProvided);
    }

}
